version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper
  kibana:
    image: bitnami/kibana:latest
    ports:
      - '5601:5601'
    environment:
      - KIBANA_ELASTICSEARCH_URL = elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    image: bitnami/elasticsearch:latest
    ports:
      - '9200:9200'